// constants/serviceCodes.js
export const SERVICE_CODES = {
    REPAIR_PLAN: "REPAIR_PLAN",
    CHECK_QUERY: "CHECK_QUERY",
    FEATURE_TREND_FORCAST: "FEATURE_TREND_FORCAST",
    PREDICT_DEVICE: "PREDICT_DEVICE",
    DIAGNOSE_FAULT: "DIAGNOSE_FAULT",
    EVALUE_STATE: "EVALUE_STATE"
};
